version: "3.7"

services:
  frontend:
    build: ./Streamlit
    ports:
      - 8501:8501
    networks: 
      AIservice: 
        aliases: 
          - streamlit.docker
    depends_on:
      - backend
      
  backend:
    build:
      context: ./
      dockerfile: ./FastAPI/Dockerfile
    ports:
      - 8000:8000
    networks: 
      AIservice: 
        aliases: 
          - fastapi.docker

networks:
  AIservice:
    driver: bridge