version: "3.7"

services:
  # Frontend - Streamlit app
  frontend:
    build: ./Streamlit
    ports:
      - 8501:8501
    depends_on:
      - backend
  # Backend - FastAPI and uvicorn
  backend:
    build:
      context: ./
      dockerfile: ./FastAPI/Dockerfile
    ports:
      - 8000:8000
    networks: 
      AIservice: 
        aliases: 
          - fastapi.docker

networks:
  AIservice:
    driver: bridge